
export const GET_SHOPS_INFO = 'GET_SHOPS_INFO';
export const GET_SHOPS_FILTER_FIELDS = 'GET_SHOPS_FILTER_FIELDS';
export const GET_SHOPS_SEARCH_FIELDS = 'GET_SHOPS_SEARCH_FIELDS';
export const GET_SHOPS_SORTING_FIELDS = 'GET_SHOPS_SORTING_FIELDS';
